Initial implementation
wso2-extensions/siddhi-io-ethereum pull request #1
Opened 2019-05-17 04:49 UTC by Lawshiga

## Purpose
>Ethereum is an open-source, public, blockchain-based distributed computing platform. This connector is used to listen to ethereum events.

## Goals
> This connector allows the user to receive block data and transaction data from ethereum blockchain.

## Approach
> Developed this ethereum connector using web3j.

## User stories
> User story of Ethereum connector for SP,
https://docs.google.com/document/d/1ld_YQY7zvyt5Kctgd7U-YHa0wEcg8Mn5uqh4h6ka-Ek/edit
## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information : 90%
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> JDK versions: JDK 8, operating system: ubuntu 16.04 LTS
 
## Learning
> https://docs.web3j.io/
https://github.com/ethereum/wiki/wiki/JSON-RPC

2019-05-17 05:55 UTC, BuddhiWathsala requested changes
Please remove unwanted files 
- `component/.attach_pid6313`
- `docs/about/license.md`
- `docs/api/.md`
- `docs/license.md`

2019-05-17 05:58 UTC, BuddhiWathsala commented on component/src/main/java/org/wso2/extension/siddhi/io/ethereum/util/EthereumUtil.java
> +    // to create filtering
Better to add comments like [this](https://github.com/siddhi-io/siddhi-io-http/blob/master/component/src/main/java/io/siddhi/extension/io/http/source/HttpRequestSource.java#L548)

2019-05-17 06:02 UTC, niruhan requested changes

2019-05-17 06:02 UTC, niruhan commented on component/src/test/java/org/wso2/extension/siddhi/io/ethereum/source/TestCaseOfEthereumSource.java
> +                "uri = 'ws://localhost:8546', \n" +
are you starting ethereum publisher locally by yourself? This test file should be able to run as it is on any machine so if you are starting by yourself please do it programatically inside this test case class

2019-05-17 06:38 UTC, niveathika requested changes

2019-05-17 06:38 UTC, niveathika commented on README.md
> +
Complete readme

2019-05-17 06:38 UTC, niveathika commented on docs/images/siddhi-logo-w.svg
> +  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
License Year, check in other places

2019-05-17 06:38 UTC, niveathika commented on mkdocs.yml
> +site_name: Siddhi-IO-Ethereum
Use new site updated mkdoc file

2019-05-17 06:38 UTC, niveathika commented on pom.xml
> +                <groupId>org.wso2.carbon.maven</groupId>
Remove unnecessary plugin

2019-05-17 06:44 UTC, minudika requested changes

2019-05-17 06:44 UTC, minudika commented on docs/images/siddhi-logo-w.svg
> +  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
license should be updated

2019-05-17 06:44 UTC, minudika commented on docs/images/siddhi-logo.svg
> +  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
the license should be updated. check and fix other places as well

2019-05-17 06:44 UTC, minudika commented on pom.xml
> +        <siddhi.version>4.5.5</siddhi.version>
use the latest siddhi version

2019-05-17 06:44 UTC, minudika commented on component/src/test/java/org/wso2/extension/siddhi/io/ethereum/source/TestCaseOfEthereumSource.java
> +        log.info("pause");
Please put some context to these logs..

2019-05-17 10:26 UTC, ramindu90 commented on component/src/main/java/org/wso2/extension/siddhi/io/ethereum/util/EthereumUtil.java
> +
lets remove these unnecessary spaces on top of each method

2019-08-06 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wso2-extensions/siddhi-io-ethereum?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wso2-extensions/siddhi-io-ethereum?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wso2-extensions/siddhi-io-ethereum?pullRequest=1) it.</sub>

2019-12-17 14:13 UTC, mohanvive approved these changes

2019-12-17 14:50 UTC, merged